### PR TITLE
Feature/67 convert to app module

### PR DESCRIPTION
**Pull request by gregdeane**
#67 

This represents the base structure going forward. As we address each component, we need to move the actions, constants, and reducers into the specific directories.

For now, actions, constants, and reducers are still in the global context.

### CODE REVIEW

**Comment by dami-gg** [comment]
Does it make sense to name index.js --> navigation.module.js? Perhaps yes, though then I'd also change every component to that naming schema (can be in a different issue)

**Comment by dami-gg** [comment]
Regarding constants we'll remove BusinessPartnerTypes.js soon, it's not going to be used like that anymore. And we should add a constant for the cookie name.

**Comment by gregdeane** [comment]
Yes, we should use the `xxx.module.js` naming throughout. But I'm not sure which index.js file you mean. My file is called `navigation.module.js`.

I think we should refactor with each directory that we touch. We shouldn't use this branch.

**Comment by dami-gg** [comment]
Fine for me, rest till tomorrow man ;)

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
@dami-gg After some sleep, I understand your question a little differently. I believe you mean something like "should we name our files `xxx.module.js` when `index.js` is simpler, especially when using `import`?"

Although a bit more verbose, I think this way is much cleaner and more self-explanatory. I'd like to stick to `xxx.module.js` style.

**Comment by gregdeane** [comment]
👍

**Pull request merged**
