### PR TITLE
Feature/157 ux adjustments

### LINKED ISSUE #157: UX adjustments
Provided by Thomas Naegele:

desktop:

- select business partner and user menu overlays lack box-shadow: 0 2px 8px 0 rgba(0, 0, 0, 0.2);
- the overlays are not vertically aligned (and opening one should close the other) --> #110 and #164 
- business partner overlay padding should be 24px
- business partner overlay title should have margin-bottom: 12px
- this might be a new requirement but I would suggest to remove auxiliary text "use the search field above to find business partners". it is somewhat redundant and doesn't add a lot of value to this small UI component.
- clicking anywhere outside of overlays should close them --> #110 
- second navigation row with application names: please add current active state on :hover as well
- when select business partner overlay opens, please focus on search input field
- same for nanorep, if possible

mobile:

- opening and closing the navigation makes the "navigation demo" label jump a couple of pixels left/right (i think icon close is too close to zalando logo)
- add hover effect to mobile as well (for when people don't use maximized windows on small laptops)

In general it looks great! there's a few glitches on mobile with touch scrolling/momentum and layering but it is super difficult to bring these little details to excellence. We shouldn't tackle this before having a critical mass of mobile users.

### PR DESCRIPTION
**Pull request by dami-gg**
Fixes #157

### CODE REVIEW

**Comment by frontendherodk** [comment]
Everything looks great except for a hover on mobile. If you hover on the text "help" with no-touch the cursor is not a pointer. It's a small thing but I think we should fix it.

**Comment by dami-gg** [comment]
@frontendherodk fixed!

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
