### PR TITLE
Feature/65 implement thunk

### PR DESCRIPTION
**Pull request by dami-gg**
#65 #71  Remaining part to handle the business partner verification process

### CODE REVIEW

**Comment by gregdeane** [comment]
I added some tests and fixed other tests but do you mind also adding any missing tests for the code you wrote?

**Comment by dami-gg** [comment]
Oh I had fixed those tests too :/

**Comment by dami-gg** [comment]
I don't really know how to test thunks and right now maybe it's not the best moment since we're involved in the restructuration so maybe we can add them later?

**Comment by gregdeane** [comment]
Sorry about the confusion with tests. I thought you had pushed all your changes before you went to lunch.

**Comment by gregdeane** [comment]
We can add the tests later but once the restructure is complete, let's commit to unit tests as a part of all PR's.

Thx!

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
