### PR TITLE
chore(karma): setup karma tests runner

### PR DESCRIPTION
**Pull request by dami-gg**
Relates to #20

I'm pretty sure this can be improved but at least I've made it run tests with karma. Let me know what you think and we can keep extending and improving it.

### CODE REVIEW

**Comment by frontendherodk** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Comment by dami-gg** [comment]
@frontendherodk please check it again, there was a conflict

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
