### PR TITLE
chore(build): added production flag for webpack

### LINKED ISSUE #188: Minify distribution files
We're not currently minifying the distribution file

### PR DESCRIPTION
**Pull request by frontendherodk**
Fixes #188

Reading through the documentation of webpack I don't believe that we will get any added benefits by splitting the build into different files.

Adding the production flag will do the job for us for now.

We can always revise in the future if it doesn't cover our needs.

### CODE REVIEW

**Comment by dami-gg** [comment]
It's working as expected. However I've realised we're also adding the dress-code fonts to the distribution files which we don't need there.

Could you please remove them too either on this PR or in a new one? It's up to you where. Thanks

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
Looks like we should have two different configs anyway to get rid of the fonts. 
I'll create a base config and adjust prod and dev accordingly.

**Comment by frontendherodk** [comment]
Since we decided not to distribute minified files this pull request doesn't really make sense anymore. I'll open another issue for the problem with the fonts since it seems like a more complex case that shouldn't block us from releasing navigation

**Pull request closed without merging**
