### PR TITLE
chore(prettier): set up prettier and place webpack files in config

### LINKED ISSUE #214: Use prettier
https://github.com/prettier/prettier

### PR DESCRIPTION
**Pull request by dami-gg**
Closes #214

### CODE REVIEW

**Comment by frontendherodk** [comment]
So Prettier does seem to work although I'm getting all sorts of weird side effects in my IDE. I'm not sure if it's actually helping more when it's running on every single build run. 
I guess we can try to leave it for but I think it might work better if people have the plugin installed for the IDE and we then run the plugin on eg. commits.

Let me know what you think @cjhowald & @dami-gg

**Comment by cjhowald** [comment]
It works fine for me in webstorm. The auto-format on auto-save can be a little jarring, but otherwise I have no issue with it.

**Comment by cjhowald** [comment]
Let's make a decision on the PR and merge or close it. Are we going to proceed as is or look into running prettier at other times (e.g. on commit)? @dami-gg @frontendherodk

**Comment by dami-gg** [comment]
If anyone wants to try to make it on commit it's fine for me. I tried and couldn't make it work smoothly, but didn't actually invest so much time on it so perhaps there's a better way

**Comment by frontendherodk** [comment]
I can take a look

**Comment by frontendherodk** [comment]
Im closing this in favour of #239

**Pull request closed without merging**
