### PR TITLE
chore(release): version 1.0.2

### LINKED ISSUE #205: Release 1.0.2
1.0.1 was not including distribution files and we have deleted it from NPM

### PR DESCRIPTION
**Pull request by dami-gg**
Closes #205

### CODE REVIEW

**Comment by dami-gg** [comment]
:+1:

**Comment by cjhowald** [comment]
Let's add a comment in the changelog about why we need 1.0.2. Otherwise looks goo.

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
