### PR TITLE
Feature/172 refactor search

### LINKED ISSUE #172: Refactor search component
It should be place inside business partner since it's not generic anymore and also should take the accessible products from the state and not through bindings

### PR DESCRIPTION
**Pull request by dami-gg**
Closes #172

### CODE REVIEW

**Comment by dami-gg** [comment]
I have extended the issue description to work on this branch so please don't review it yet

**Comment by dami-gg** [comment]
Ready to be reviewed

**Comment by frontendherodk** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
