### PR TITLE
Test/124 tests help search

### LINKED ISSUE #119: Unit tests for search component

### LINKED ISSUE #124: Unit test for help and search

### PR DESCRIPTION
**Pull request by frontendherodk**
Fixes #119 #121

### CODE REVIEW

**Comment by frontendherodk** [comment]
👎  missing the help dispatch

**Comment by dami-gg** [comment]
Good work, nice to see that we have a new Unit testing advocate in the team ;)

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
