### PR TITLE
Feature/50 source maps in browser

### PR DESCRIPTION
**Pull request by gregdeane**
#50 

~~Includes changes from PR #49. I will merge `master` into this branch as soon as that PR is ready.~~

### CODE REVIEW

**Comment by dami-gg** [comment]
Awesome, I really needed that to be back :D

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
Haha!! Good to know. ;)

**Comment by gregdeane** [comment]
👍

**Pull request merged**
