### PR TITLE
Feature/180 remove angular

### LINKED ISSUE #180: Remove angular from distribution files
Otherwise the client application tries to load angular twice. Check integration on MVP

### PR DESCRIPTION
**Pull request by dami-gg**
Fixes #180 

The only way to prove it was working was testing it in the MVP, that's why I added some distribution files, since NPM linking is still not working

I wonder whether we should do the same for the SC-Login and SC-Communicator and extend the README stating that those are required dependencies (which any case are already to be met by any client application of the navigation...). 

So keep this PR as discussion point, not ready to merge yet

What do you think @frontendherodk @cjhowald ?

### CODE REVIEW

**Comment by cjhowald** [comment]
I agree we should not bundle login and communicator into this library. Each library should distribute just its own code and expect the hosting application to provide the other dependent libraries.

**Comment by frontendherodk** [comment]
Jep, I agree. We don't want to bundle more files that necessary.

**Comment by dami-gg** [comment]
I've done a bit more research and the problem comes from importing ngstorage in vendor/index.js. Removing it causes the application to break since it's needed in common.js which has the dependency of solutioncenter.login

I'll check that tomorrow again because I ran out of ideas but would be nice that you think about it in case you have some and we can fix it by this week

**Comment by cjhowald** [comment]
@dami-gg After further investigation yesterday, it looks like webpack has a way to exclude dependencies from your bundle while requiring that the host includes them, [Externals](https://webpack.js.org/configuration/externals/). I took a first pass at setting this up by restoring vendor and adding externals to the webpack config. It still needs some work, so please take a look.

This [webpack guide on authoring libraries](https://webpack.js.org/guides/author-libraries/#components/sidebar/sidebar.jsx) was also useful.

**Comment by cjhowald** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
