### PR TITLE
feat(endpoint): use new endpoint with filtering capabilities

### LINKED ISSUE #106: Use new API endpoints which support filtering
We must filter the products and applications we get from backend to hide Solution Center applications

https://github.bus.zalan.do/norris/epics/issues/20

### PR DESCRIPTION
**Pull request by dami-gg**
Closes #106

There's nothing else to change from FE side but we need to test that it works as expect when BE fixes the typo in their side

### CODE REVIEW

**Comment by dami-gg** [comment]
:-1:

**Comment by frontendherodk** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
👍  Good job

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
