### PR TITLE
Bugfix/111 positioning help menu

### LINKED ISSUE #111: Fix positioning of Help menu

### PR DESCRIPTION
**Pull request by frontendherodk**
Fixes #111

### CODE REVIEW

**Comment by dami-gg** [comment]
The hamburger button icon should be bigger and we should remove some padding top on the user block on mobile view. The rest is fine!

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
