### PR TITLE
Feature/214 setup prettier

### LINKED ISSUE #214: Use prettier
https://github.com/prettier/prettier

### PR DESCRIPTION
**Pull request by frontendherodk**
Fixes #214 

Note: The reason for all the file changes is because I ran prettier on the entire code base.

### CODE REVIEW

**Comment by dami-gg** [comment]
perhaps we should eventually check how to customize the rules a bit... this for example doesn't look that much readable for me and I'd say for anyone:

image

**Comment by dami-gg** [comment]
You forgot to add prettier as dev dependency

**Comment by dami-gg** [comment]
Besides that it works correctly, please add that and I'll approve it

**Comment by dami-gg** [comment]
I've done it myself ;)

**Comment by dami-gg** [comment]
:+1:

**Comment by frontendherodk** [comment]
About customizing, there are limited rules that you can actually change for good reasons. 
I don't think the problem is with Prettier in the example you gave but more how we wrote the code. 
That said we can take a look at the rules we can customize :)

And thanks for adding the dependency :)

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
